# -*- coding: utf-8 -*-
#
# Copyright (c) ZeroC, Inc. All rights reserved.
#
#
# Ice version 3.7.10
#
# <auto-generated>
#
# Generated from file `IM.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module Demo
_M_Demo = Ice.openModule('Demo')
__name__ = 'Demo'

_M_Demo._t_DMM = IcePy.defineValue('::Demo::DMM', Ice.Value, -1, (), False, True, None, ())

if 'DMMPrx' not in _M_Demo.__dict__:
    _M_Demo.DMMPrx = Ice.createTempClass()
    class DMMPrx(Ice.ObjectPrx):

        def printIDN(self, IDN, context=None):
            return _M_Demo.DMM._op_printIDN.invoke(self, ((IDN, ), context))

        def printIDNAsync(self, IDN, context=None):
            return _M_Demo.DMM._op_printIDN.invokeAsync(self, ((IDN, ), context))

        def begin_printIDN(self, IDN, _response=None, _ex=None, _sent=None, context=None):
            return _M_Demo.DMM._op_printIDN.begin(self, ((IDN, ), _response, _ex, _sent, context))

        def end_printIDN(self, _r):
            return _M_Demo.DMM._op_printIDN.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_Demo.DMMPrx.ice_checkedCast(proxy, '::Demo::DMM', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_Demo.DMMPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::Demo::DMM'
    _M_Demo._t_DMMPrx = IcePy.defineProxy('::Demo::DMM', DMMPrx)

    _M_Demo.DMMPrx = DMMPrx
    del DMMPrx

    _M_Demo.DMM = Ice.createTempClass()
    class DMM(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Demo::DMM', '::Ice::Object')

        def ice_id(self, current=None):
            return '::Demo::DMM'

        @staticmethod
        def ice_staticId():
            return '::Demo::DMM'

        def printIDN(self, IDN, current=None):
            raise NotImplementedError("servant method 'printIDN' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_Demo._t_DMMDisp)

        __repr__ = __str__

    _M_Demo._t_DMMDisp = IcePy.defineClass('::Demo::DMM', DMM, (), None, ())
    DMM._ice_type = _M_Demo._t_DMMDisp

    DMM._op_printIDN = IcePy.Operation('printIDN', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0),), (), None, ())

    _M_Demo.DMM = DMM
    del DMM

# End of module Demo
